- label: sad
  title: "Me, Myself, and AI: The Situational Awareness Dataset (SAD) for LLMs"
  date: 2024-07-08
  description: "We build a comprehensive benchmark to measure situational awareness in LLMs. It consists of 16 tasks, which we group into 7 categories and 3 aspects of situational awareness (self-knowledge, situational inferences, and taking actions)."
  math: false
  tags: ["ai", "research", "paper"]
  coauthors:
    [
      "Rudolf Laine",
      "Jan Betley",
      "Kaivu Hariharan",
      "Jeremy Scheurer",
      "Mikita Balesni",
      "Alex Meinke",
      "Marius Hobbhahn",
      "Owain Evans",
    ]
  elsewhere:
    [
      "https://www.lesswrong.com/posts/YsCRXZYr5DcJ84XHq/me-myself-and-ai-the-situational-awareness-dataset-sad-for",
      "https://situational-awareness-dataset.org/",
      "https://arxiv.org/abs/2407.04694"
      ]

- label: zero-to-one
  title: "Book Summary: Zero to One"
  date: 2024-12-26
  description: "A summary of Peter Thiel's book, Zero to One."
  math: false
  tags: ["books", "startups"]
  elsewhere:
    [
      "https://www.lesswrong.com/posts/7LZHS4afrXCNuuGK9/book-summary-zero-to-one"
    ]

- label: favourites
  title: "Product recommendations"
  date: 2025-01-11
  description: "A list of some of my favourite things."
  math: false
  tags: ["productivity"]


- label: caps-lock
  title: "You should remap your caps lock key"
  date: 2024-12-01
  description: "Caps lock is a waste of space."
  math: false
  tags: ["productivity"]
  elsewhere:
    [
      "https://www.lesswrong.com/posts/hPLvZsNZGsQSLfMee/remap-your-caps-lock-key"
    ]

- label: frontier-lab
  title: "Reasons for and against working on technical AI safety at a frontier AI lab"
  date: 2024-12-26
  description: "I am about to start working on a frontier lab safety team. This post presents a varied set of perspectives that I collected and thought through before accepting my offer."
  math: false
  tags: ["careers", "ai"]
  elsewhere: ["https://www.lesswrong.com/posts/cyYgdYJagkG4HGZBk/reasons-for-and-against-working-on-technical-ai-safety-at-a",
  "https://forum.effectivealtruism.org/posts/vCZxmMP2dDjxFByrD/reasons-for-and-against-working-on-technical-ai-safety-at-a"]

- label: phd
  title: "You should consider applying to PhDs (soon!)"
  date: 2024-11-29
  description: "Junior AI safety researchers should consider applying to PhDs soon."
  math: false
  tags: ["careers", "ai"]
  elsewhere: [
    "https://www.lesswrong.com/posts/PdtkXcgbRpdHWRNt6/you-should-consider-applying-to-phds-soon"
  ]

- label: activation-space-interpretability
  title: "Activation space interpretability may be doomed"
  date: 2025-01-08
  description: "There may be a fundamental problem with interpretability work that attempts to understand neural networks by decomposing their individual activation spaces in isolation: It seems likely to find features of the activations - features that help explain the statistical structure of activation spaces, rather than features of the model - the features the model’s own computations make use of."
  math: true
  tags: ["ai", "interpretability", "research"]
  elsewhere:
    ["https://www.lesswrong.com/posts/gYfpPbww3wQRaxAFD/activation-space-interpretability-may-be-doomed"]
  coauthors:
    ["Lucius Bushnaq"]

- label: pos-sae
  title: "Understanding positional features in layer 0 SAEs"
  date: 2024-07-29
  description: ""
  math: true
  tags: ["ai", "interpretability", "research"]
  elsewhere:
    ["https://www.lesswrong.com/posts/ctGeJGHg9pbc8memF/understanding-positional-features-in-layer-0-saes"]
  coauthors:
    ["Yeu-Tong Lau"]

- label: rmu
  title: "Unlearning via RMU is mostly shallow"
  date: 2024-07-23
  description: ""
  math: true
  tags: ["ai", "interpretability", "research"]
  elsewhere:
    ["https://www.lesswrong.com/posts/6QYpXEscd8GuE7BgW/unlearning-via-rmu-is-mostly-shallow"]
  coauthors:
    ["Andy Arditi"]

- label: faithfulness
  title: "Transformer circuit faithfulness metrics are not robust"
  date: 2024-07-12
  description: ""
  math: true
  tags: ["ai", "interpretability", "research", "paper"]
  elsewhere:
    ["https://www.lesswrong.com/posts/kp5h6khwrK47psMaA/transformer-circuit-faithfulness-metrics-are-not-robust",
    "https://arxiv.org/abs/2407.08734"]
  coauthors:
    ["Joseph Miller", "William Saunders"]

- label: intellectual-progress-2024
  title: "Intellectual progress in 2024"
  date: 2025-01-11
  description: ""
  math: false
  tags: ["personal"]
  
- label: cuplc
  title: "CUPLC website enhancements"
  date: 2023-09-01
  description: ""
  math: false
  tags: ["sport"]

- label: essay
  title: "Part III Essay: The search for CMB B-mode polarization from inflationary gravitational waves"
  date: 2021-06-01
  description: ""
  math: false
  tags: ["physics"]

- label: review
  title: "Open problems in mechanistic interpretability"
  date: 2025-01-29
  description: ""
  math: false
  tags: ["interpretability", "ai", "paper"]
  coauthors: ["Lee Sharkey"]
  elsewhere: [
    "https://arxiv.org/abs/2501.16496",
    "https://www.lesswrong.com/posts/fqDzevPyw3GGaF5o9/paper-open-problems-in-mechanistic-interpretability"
  ]

- label: dd
  title: "Detecting strategic deception using linear probes"
  date: 2025-02-06
  description: ""
  math: false
  tags: ["interpretability", "ai", "paper"]
  coauthors: ["Nix Goldowsky-Dill", "Stefan Heimersheim", "Marius Hobbhahn"]
  elsewhere: [
"https://arxiv.org/abs/2502.03407",
"https://www.lesswrong.com/posts/9pGbTz6c78PGwJein/detecting-strategic-deception-using-linear-probes"
  ]

- label: gdm
  title: "Joining Google DeepMind"
  date: 2025-02-17
  description: ""
  math: false
  tags: ["careers", "ai", "interpretability"]
  elsewhere: [
    "https://www.linkedin.com/posts/bilalchughtai_im-excited-to-share-that-im-starting-a-activity-7306735125826850816-UJpi?utm_source=share&utm_medium=member_desktop&rcm=ACoAACy6rLMBE3sQAk8sLKQF2roS-gHr056HXSU"
  ]

- label: bookshelf
  title: "Bookshelf"
  date: 2025-04-12
  description: ""
  math: false
  tags: ["books"]

- label: hd
  title: "My health dashboard"
  date: 2025-06-15
  description: ""
  math: false
  tags: ["health"]

- label: e2p
  title: "everything2prompt"
  date: 2025-08-03
  description: ""
  math: false
  tags: ["ai", "productivity"]
  elsewhere:
    [
      "https://github.com/bilal-chughtai/everything2prompt",
      "https://docs.google.com/presentation/d/1o4qZ1xlcn6tKxTNmNRS8oQdSLOd8emWLaAuNcfbsh9A/edit?slide=id.g371af394405_0_0#slide=id.g371af394405_0_0"
    ]

- label: todo
  title: "An opinionated guide to building a good to-do system"
  date: 2025-08-05
  description: ""
  math: false
  tags: ["productivity"]
  elsewhere: [
    "https://www.lesswrong.com/posts/4dkzn2jdW4jCg8m8Y/an-opinionated-guide-to-building-a-good-to-do-system",
    "https://forum.effectivealtruism.org/posts/rCsC9iiLdHJkC8GmF/an-opinionated-guide-to-building-a-good-to-do-system",
    "https://www.linkedin.com/posts/bilalchughtai_my-to-do-system-is-by-far-the-most-important-activity-7358635639925293056-R_Uf?utm_source=share&utm_medium=member_desktop&rcm=ACoAACy6rLMBE3sQAk8sLKQF2roS-gHr056HXSU",
    "https://x.com/bilalchughtai_/status/1952867852224217591"
  ]
